### ISSUE TITLE
Database read issue for PSRCAT versions >=1.66

### ISSUE THREAD

**Issue by bwmeyers** [mattpitkin/psrqpy#112]
I've just been playing around with this and when calling the `get_catalogue()` function with versions  `>=1.66 ` get the following error:
```python
In [8]: psrqpy.utils.get_catalogue(cache=False, version="1.66")
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In [8], line 1
----> 1 psrqpy.utils.get_catalogue(cache=False, version="1.66")

File ~/code/mwa/venv/lib/python3.8/site-packages/psrqpy/utils.py:93, in get_catalogue(path_to_db, cache, update, pandas, version)
     91 # get the tarball
     92 try:
---> 93     dbtarfile = download_atnf_tarball(
     94         atnftarball, usecache=cache, version=version
     95     )
     96 except RuntimeError as e:
     97     raise IOError(
     98         f"Problem accessing ATNF catalogue tarball: {atnftarball}\n{e}"
     99     )

File ~/code/mwa/venv/lib/python3.8/site-packages/psrqpy/utils.py:388, in download_atnf_tarball(url, usecache, version)
    385     raise RuntimeError("Error downloading pulsar catalogue: {}".format(str(e)))
    387 if tarfile.status_code != 200:
--> 388     raise RuntimeError("Error downloading pulsar catalogue: {}".format(str(e)))
    390 if not os.path.exists(CACHEDIR):
    391     try:

UnboundLocalError: local variable 'e' referenced before assignment
```
including when I leave it as the default `latest` where it highlights that there may well be a malformed entry in the catalogue itself that it making the package balk. e.g., 

```python
In [9]: psrqpy.utils.get_catalogue(cache=False)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/code/mwa/venv/lib/python3.8/site-packages/psrqpy/utils.py:161, in get_catalogue(path_to_db, cache, update, pandas, version)
    160 try:
--> 161     float(val)
    162 except ValueError:

ValueError: could not convert string to float: '56,451.27'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In [9], line 1
----> 1 psrqpy.utils.get_catalogue(cache=False)

File ~/code/mwa/venv/lib/python3.8/site-packages/psrqpy/utils.py:163, in get_catalogue(path_to_db, cache, update, pandas, version)
    161     float(val)
    162 except ValueError:
--> 163     raise ValueError("Value with error is not convertable to a float")
    165 if dataline[2][0] == "-" or "." in dataline[2]:
    166     # negative errors or those with decimal points are absolute values
    167     scalefac = 1.0

ValueError: Value with error is not convertable to a floa
```
It _looks_ like it's an error introduced into one or more entries in the catalogue, or perhaps an edge case?

For reference, I'm using the version downloaded from `pip`: v1.2.2

**Comment by mattpitkin** [comment]
@bwmeyers thanks for reporting this. The first error you're seeing was fixed by #110, but unfortunately I've not created a new release containing this yet (v1.66 gives an error as the file does not exist for downloading!)

The error for the "latest" catalogue version is due to Dick Manchester updating the catalogue last night. These updates often contain minor errors and Dick now know about a couple of these which he should be fixing within the next day or so. So, hopefully it'll work again soon.

**Comment by bwmeyers** [comment]
Aha, I see. Thanks for the response :) Maybe we should switch to downloading from the GitHub repo. rather than PyPI :sweat_smile: 

I did also try with v1.67 and v1.68 explicitly specified, and they both failed in the same way, so I guess that the malformed PSRCAT entry has been around since v1.67.

**Comment by mattpitkin** [comment]
I generally try and keep to PyPI release up-to-date, but obviously this change slipped through without a new release.

> I did also try with v1.67 and v1.68 explicitly specified, and they both failed in the same way, so I guess that the malformed PSRCAT entry has been around since v1.67.

The problems with v1.66 and v1.67 is that they aren't provided on the archived versions page https://www.atnf.csiro.au/people/pulsar/psrcat/download.html where the others are listed. I might ask Dick if he can add them.

**Comment by mattpitkin** [comment]
@bwmeyers It looks like the v1.68 catalogue is now working :smiley:

**Comment by mattpitkin** [comment]
I'll create a new psrqpy release later today.

**Comment by mattpitkin** [comment]
@bwmeyers The tarballs for v1.66 and v1.67 are now available on the catalogue [download page](https://www.atnf.csiro.au/research/pulsar/psrcat/download.html), so psrqpy should be able to access them now.

**Comment by bwmeyers** [comment]
Great, thanks @mattpitkin! I can confirm from my end that things are now working as expected with the default "latest" for the queries, etc. But good to know the previous version tarballs are explicitly accessible now :)
