### ISSUE TITLE
parsed psrcat database (in v2.0.0) version is None

### ISSUE THREAD

**Issue by noREAVER** [mattpitkin/psrqpy#131]
Catalog version 2.0.0 has an extra space in the 1st header/meta line `# CATALOG` which makes version `None` when working with the catalog.
If changed to `#CATALOG` like on previous versions it works fine.

**Comment by mattpitkin** [comment]
Thanks for reporting this. I'll fix this.

**Comment by mattpitkin** [comment]
I've fixed this and created a new psrqpy release with the fix.
