### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Iman-Talebi** [mattpitkin/psrqpy#138]
I run the command: 

'query = psrqpy.QueryATNF()'

and get the error:

ValueError                                Traceback (most recent call last)
File [~/pyenv/base/lib/python3.10/site-packages/psrqpy/utils.py:163](http://localhost:8888/home/iman/pyenv/base/lib/python3.10/site-packages/psrqpy/utils.py#line=162), in get_catalogue(path_to_db, cache, update, pandas, version)
    162 try:
--> 163     float(val)
    164 except ValueError:

ValueError: could not convert string to float: 'HAVE'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
File [~/pyenv/base/lib/python3.10/site-packages/psrqpy/search.py:351](http://localhost:8888/home/iman/pyenv/base/lib/python3.10/site-packages/psrqpy/search.py#line=350), in QueryATNF.get_catalogue(self, path_to_db, cache, update, overwrite, version)
    350 try:
--> 351     dbtable = get_catalogue(path_to_db=path_to_db, cache=cache,
    352                             update=update, pandas=True,
    353                             version=version)
    354 except Exception as e:

File [~/pyenv/base/lib/python3.10/site-packages/psrqpy/utils.py:165](http://localhost:8888/home/iman/pyenv/base/lib/python3.10/site-packages/psrqpy/utils.py#line=164), in get_catalogue(path_to_db, cache, update, pandas, version)
    164 except ValueError:
--> 165     raise ValueError("Value with error is not convertable to a float")
    167 if dataline[2][0] == "-" or "." in dataline[2]:
    168     # negative errors or those with decimal points are absolute values

ValueError: Value with error is not convertable to a float

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
Cell In[11], line 1
----> 1 query = psrqpy.QueryATNF()

File [~/pyenv/base/lib/python3.10/site-packages/psrqpy/search.py:216](http://localhost:8888/home/iman/pyenv/base/lib/python3.10/site-packages/psrqpy/search.py#line=215), in QueryATNF.__init__(self, params, condition, psrtype, assoc, bincomp, exactmatch, sort_attr, sort_order, psrs, include_errs, include_refs, adsref, loadfromfile, loadquery, loadfromdb, cache, checkupdate, circular_boundary, coord1, coord2, radius, frompandas, fromtable, version)
    214 # download and cache (if requested) the database file
    215 try:
--> 216     _ = self.get_catalogue(path_to_db=loadfromdb, cache=cache,
    217                            update=checkupdate, version=version)
    218 except IOError:
    219     raise IOError("Could not get catalogue database file")

File [~/pyenv/base/lib/python3.10/site-packages/psrqpy/search.py:355](http://localhost:8888/home/iman/pyenv/base/lib/python3.10/site-packages/psrqpy/search.py#line=354), in QueryATNF.get_catalogue(self, path_to_db, cache, update, overwrite, version)
    351     dbtable = get_catalogue(path_to_db=path_to_db, cache=cache,
    352                             update=update, pandas=True,
    353                             version=version)
    354 except Exception as e:
--> 355     raise RuntimeError("Problem getting catalogue: {}".format(str(e)))
    357 if not cache:
    358     if not overwrite:

RuntimeError: Problem getting catalogue: Value with error is not convertable to a float

How solve it?

**Comment by mattpitkin** [comment]
Thanks for reporting this. I think there must be an error in the current pulsar catalogue file. Could you try using an older catalogue version, e.g.,

```python
query = psrqpy.QueryATNF(version="2.2.0")
```

and let me know if that still works for you?

**Comment by mattpitkin** [comment]
It seems that the latest version of the `psrcat.db` file that psrqpy reads the information from contains a few instances of lines with:

```
WARNING: HAVE 0 ERROR
```

These lines break the parsing of the file. I've let the ATNF catalogue maintainers know about this issue. They'll either be able to remove the offending lines, or I'll make a new psrqpy release that ignores lines that start with "WARNING".

**Comment by Iman-Talebi** [comment]
Hello;
thanks for the rapid response. yes, the problem is from the catalog's latest version because it works with the older version as you mentioned.

**Comment by mattpitkin** [comment]
I've created a new psrqpy release (v1.2.10), which is now available on PyPI for pip installation. This release will work with the current catalogue version.
