### ISSUE TITLE
List index out of range error on first query

### ISSUE THREAD

**Issue by emmacarli** [mattpitkin/psrqpy#140]
Hello!
I've just tried to install psrqpy from source (Python 3.10.14) and conda (Python 3.9.19 and Python 3.10.14) on a Mac machine, then using pip on a Linux machine (Python 3.10.4). The install and import goes fine for all of them but when I try to run this simple query
```
import psrqpy
psrqpy.QueryATNF(params=['P0'], psrs=['J0045-7319']).p0
```
or even just an empty query, I get the following error for all:
```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py310/lib/python3.10/site-packages/psrqpy/search.py", line 351, in get_catalogue
    dbtable = get_catalogue(path_to_db=path_to_db, cache=cache,
  File "/opt/anaconda3/envs/py310/lib/python3.10/site-packages/psrqpy/utils.py", line 144, in get_catalogue
    psrlist[-1][dataline[0]] = float(dataline[1])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ecarli/Desktop/Repositories/MeerTIME_Utils/RFI/RFI_stats_median_slow_pulsars.py", line 33, in <module>
    if psrqpy.QueryATNF(params=['P0'], psrs=[pulsar]).p0 < 0.07: #skip pulsars with periods less than 80ms which I would call fast pulsars
  File "/opt/anaconda3/envs/py310/lib/python3.10/site-packages/psrqpy/search.py", line 216, in __init__
    _ = self.get_catalogue(path_to_db=loadfromdb, cache=cache,
  File "/opt/anaconda3/envs/py310/lib/python3.10/site-packages/psrqpy/search.py", line 355, in get_catalogue
    raise RuntimeError("Problem getting catalogue: {}".format(str(e)))
RuntimeError: Problem getting catalogue: list index out of range
```
When I try to debug I find that if I run `utils.py`'s `get_catalogue` on just the first pulsar of the catalogue it seems to work without issues (I think). So I'm not sure which part exactly this is coming from.
Thanks in advance!
Emma

**Comment by mattpitkin** [comment]
It looks like there's been a catalogue update today that has broken things. If you try the query call including the argument `version="2.4.0"` it should work. I'll need to look into the problems with the new version.

I don't thing you `psrqpy.QueryATNF(params=['P0'], psrs=[pulsar]).p0` construct with the `.p0` at the end will work though as the query is not a `DataFrame` from which columns can be accessed as attributes. You could instead do `psrqpy.QueryATNF(params=['P0'], psrs=[pulsar]).pandas.P0` which converts the table into a pandas `DataFrame`.

However, I'd recommend doing something like:

```python
slowpsrs = psrqpy.QueryATNF(condition="P0 < 0.07")

if psr in slowpsrs["PSRJ"]:
    # skip ...
```

**Comment by emmacarli** [comment]
Thanks very much, that all worked. :)

**Comment by mattpitkin** [comment]
For information, I updated psrqpy (in #141) to deal with the problem with the newest catalogue version (for at least one pulsar a `TYPE` field was given without an associated value) - I've not created a new psrqpy release with this change yet. I also contacted the catalogue maintainers, so the issue may actually get fixed on that size quickly.
