### ISSUE TITLE
Upper case parameters

### ISSUE THREAD

**Issue by GregoryAshton** [mattpitkin/psrqpy#20]
In the `QueryATNF` method, the `params` are all coerced to upper case before the query is sent. However, for some strange reason not all the parameter names used by ATNF are upper case. Some examples:

> ELong:       Ecliptic longitude (degrees)
> DecJD:       Declination (J2000) (degrees)

Could you either have these as special cases, or not have the input be case sensitive? I'm happy to submit an MR, but maybe you have some preference on how that should be handled.

**Comment by mattpitkin** [comment]
When you construct the ATNF query URL it is case insensitive, so querying with `ELong` or `ELONG` should give the same results. Are you seeing a problem where this is not working?

**Comment by GregoryAshton** [comment]
Hi Matt,

My apologies. I thought I was seeing an error when using DecJD, but I can't reproduce it now so please ignore me :)

Cheers,

**Comment by mattpitkin** [comment]
No problem.
