### ISSUE TITLE
missing SNR label in legend?

### ISSUE THREAD

**Issue by GammaRayWurst** [mattpitkin/psrqpy#22]
Hi Matt, this is really nice! Makes plotting pulsar populations very easy. I just cloned and installed per your instructions, and everything ran swimmingly except for one issue: I tried to recreate one of your plots that showed SNRs, and got a KeyError with 'SNR.' I dug around search.py and found the issue: Starting at L940 you define legend strings, but 'SNR' doesn't make it in, while it does get added into nshowtypes. Here is the full error message (without 'showSNRs' there is no error):

```
In [24]: query.ppdot(Bfield=[], showtypes=['BINARY'], showSNRs=True)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-24-d331258e9612> in <module>()
----> 1 query.ppdot(Bfield=[], showtypes=['BINARY'],showSNRs=True)

//anaconda/lib/python2.7/site-packages/psrqpy-0.4.12-py2.7.egg/psrqpy/search.pyc in ppdot(self, intrinsicpdot, excludeGCs, showtypes, showGCs, showSNRs, markertypes, deathline, deathmodel, filldeath, filldeathtype, showtau, brakingidx, tau, showB, Bfield, pdotlims, periodlims, rcparams)
    978                     markertypes[thistype]['linestyle'] = 'none'
    979                 typehandle, = ax.loglog(periods[typeidx], pdots[typeidx],
--> 980                                         label=typelegstring[thistype],
    981                                         **markertypes[thistype])
    982                 if thistype in typelegstring:

KeyError: 'SNR'

```

**Comment by mattpitkin** [comment]
Thanks for spotting this. It looks like it should be an easy fix.

**Comment by mattpitkin** [comment]
I've updated the version available on PyPI to include this fix, so if you upgrade it should be present.
