### ISSUE TITLE
Offline functionality? 

### ISSUE THREAD

**Issue by respiewak** [mattpitkin/psrqpy#36]
I was thinking it might be useful to be able to maintain functionality offline, for example with calls to the `psrcat` software or psrcat.db files. Is this already supported, is it something that has been considered, or is it something that would require a lot of reworking?

**Comment by mattpitkin** [comment]
At the moment I have a function, [`get_catalogue()`](https://psrqpy.readthedocs.io/en/latest/utils.html#psrqpy.utils.get_catalogue), that allows you to download the entire catalogue as an astropy Table. This could then be saved and used later. You can also save previous queries made with the [`QueryATNF`](https://psrqpy.readthedocs.io/en/latest/query.html#psrqpy.search.QueryATNF) class that can be re-loaded at a later time without being online.

It would be nice to have a direct Python interface the the psrcat.db file maybe through the `psrcat` software (or a Python version of `psrcat`!), but it may be relatively easy add extra abilities to the `get_catalogue` function (maybe through making it a class) that allows it to be queried in a more `psrcat`-like way.

**Comment by mattpitkin** [comment]
Also, just to note, I have an Issue #34 and related PR #35 that it to add a function that can query an astropy table using logical conditions like you might input `psrcat`.

**Comment by respiewak** [comment]
OK, I didn't see that function initially. That's pretty useful. I can see some ways in which it could be improved, though, such as including an argument for a path to an already-gunzipped psrcat.db file, to bypass a few steps. Having uncertainties would be good, too. 

I wonder if it's also possible to modify an astropy Table with additional .db files, like using `psrcat -all`. That would be very useful for me personally, and anyone who works with pulsar surveys.

**Comment by mattpitkin** [comment]
Yes, please go ahead and make a pull request.

I think I can relatively easily turn make a new class that acts like `get_catalogue` (for backwards compatibility we'd probably keep that function, but just have it create the class and return the output as an astropy table. I'll probably make the new class a subclass of the `QueryATNF` class, so it can use some of the functions that already exist. I think an `add_catalogue`-like function should also be doable - astropy Tables should easily be able to have the columns extended with new data, or add new columns if required.

**Comment by respiewak** [comment]
I think I'll close this issue and open another for changing `get_catalogue` into a class with an `add_catalogue`-like function.
