### ISSUE TITLE
Make `get_catalogue` into a class?

### ISSUE THREAD

**Issue by respiewak** [mattpitkin/psrqpy#39]
After #36, we may want to re-work `get_catalogue into a class, and make it possible to add to the table with data from additional .db files (e.g., private updated timing parameters).

**Comment by respiewak** [comment]
I think that would be better than having a separate class for `get_catalogue`. I don't have a good idea right now of how that would work, but I'll certainly contribute where I can.

**Comment by mattpitkin** [comment]
I'll have a go at changing things in the next few days and keep you in the loop (and maybe call on you for testing!)

**Comment by mattpitkin** [comment]
This will be taken care of in #41.
