### ISSUE TITLE
Parsing non-numeric values for parameters such as 'ASSOC'

### ISSUE THREAD

**Issue by respiewak** [mattpitkin/psrqpy#43]
Revised from Issue #42 -- "Parameters like 'assoc', 'type', and 'bincomp' are not easy to work with in their standard form, due to the inclusion of extra information, such as references. These could, however, be parsed to put important information (e.g., for 'assoc': 'AXP') into a new column for easy querying."

It would be best to split the information in those parameters ('type', 'assoc', 'bincomp', 'survey'?) for easier querying and sorting. For example: the 'type' "HE[cdt69,fhm+69,hjm+70]" (for the Crab pulsar) would be split into the 'type' value and reference(s).

**Comment by mattpitkin** [comment]
Yes, this would be good. A little bit of checking for square brackets in the read in value in the `get_catalogue` function should sort this. The slightly more tricky bit is allowing the `get_references` function to have multiple references for a particular value, but it's certainly doable (this part may be easier to do in the reworked API where I've started simplifying that function).

**Comment by respiewak** [comment]
I'll just make a version 1 which only puts the first reference into the REF column, and leave a "To-Do" for after we change `get_references`.

**Comment by respiewak** [comment]
Mostly there in PR #41, but could use some work to allow for inclusion of multiple values/references. Might not be possible without considerable restructuring of functions.
