### ISSUE TITLE
missing rescaling factors for glitch sizes

### ISSUE THREAD

**Issue by dbkeitel** [mattpitkin/psrqpy#44]
The rescaling factors of 1e-9 for DeltaF/F and 1e-3 for DeltaF1/F1 (and their respective error bars) from the Jodrell table are missing as of 0d6f225087e3c7b06537a0b6da1df52478815b9e:
```
import psrqpy
glitches_jodrell = psrqpy.get_glitch_catalogue()
glitches_jodrell[0]['DeltaF/F']
554.0
```
Should yield 5.54e-7.

A pypi release after that change would be much appreciated.

**Comment by mattpitkin** [comment]
@dbkeitel I've create a new release with @respiewak's fix. Let me know if the version you pull from PyPI works now.

**Comment by dbkeitel** [comment]
Yes it does, thanks to both of you!
