### ISSUE TITLE
Add parsing of the Galactic MSP table

### ISSUE THREAD

**Issue by mattpitkin** [mattpitkin/psrqpy#46]
Similarly to #9, we could add a function to get and parse [Duncan Lorimer's](https://astro.wvu.edu/people/facultystaff/dlorimer) [Galactic MSP](http://astro.phys.wvu.edu/GalacticMSPs/) [table](http://astro.phys.wvu.edu/GalacticMSPs/GalacticMSPs.txt).

**Comment by astrogewgaw** [comment]
hey @mattpitkin! i tried my hand at parsing the galactic MSPs database (in honor of them passing the 400 mark) and the results are [**here**](https://github.com/astrogewgaw/galmsps). let me know what you think! i have serialized the data from the database into JSON, so it should be easy for you to deal with as well. the data in the repository will update itself every month, thanks to a GitHub workflow.

**Comment by mattpitkin** [comment]
@astrogewgaw cool, that looks very useful. I'll try and add parsing of the MSP table into psrqpy today, so will be making use of this!
