### ISSUE TITLE
Plotting .ppdot gives two plots in Jupyter notebook

### ISSUE THREAD

**Issue by gabella** [mattpitkin/psrqpy#51]
I am running a Jupyter Notebook with Python3 and with (problem also without) the %matplotlib notebook before all my imports.  My code is 
```
psrcatParams = ['name', 'jname', 'posepoch', 'elong', 'elat', 'pmelong', 'pmelat', 'gl', 'gb', 'p0', 'p1', 
                'dist', 'assoc']
qq = QueryATNF(params=psrcatParams, condition='P0 < 30.0e-3')
```

And in the next cell
`qq.ppdot( showSNRs=True, showtypes='all', rcparams={'figure.figsize': (8, 7), 'figure.dpi': 111} )
`
Which gives two plots, one after the other.  They look identical to me and are what I expect from the manual.  Oh the defaults on my laptop are also huge plots, hence the rcparams above.

By the way, thanks for the code.  It is a great way to get an ATNF query into pandas.
bill e.g.
ps--Running on Fedora 29 with bleeding edge everything, I would guess.

**Comment by mattpitkin** [comment]
I have seen this sort of thing before, but can't remember the cause or solution! It could be a Matplotlib backend issue. Could you see what happens if you use `%matplotlib inline` that than `%matplotlib inline`?

**Comment by mattpitkin** [comment]
Actually looking at [this thread](https://github.com/statsmodels/statsmodels/issues/1265), it looks like catching the returned object might do the trick, so try

```python
fig = qq.ppdot( showSNRs=True, showtypes='all', rcparams={'figure.figsize': (8, 7), 'figure.dpi': 111} )
```

**Comment by gabella** [comment]
Just tried your last suggestion and yup, only one plot.  Thanks.  By-the-way, that is a very pretty plot.  Nice fix.

**Comment by mattpitkin** [comment]
Nice to see that it worked :smile:
