### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by fleaf5** [mattpitkin/psrqpy#52]
Hi, I am using python3.6 (and I am sure that pandas has been installed), when I try to use the package, I keep getting the following error message:

~/.local/lib/python3.6/site-packages/psrqpy/search.py in parse_assoc(self)
    988 
    989         ASSOCnew = self.catalogue['ASSOC'].copy()
--> 990         idxassoc = ~ASSOCnew.isna()
    991 
    992         # Set references first

/opt/python/intelpython3/lib/python3.6/site-packages/pandas/core/generic.py in __getattr__(self, name)
   3079             if name in self._info_axis:
   3080                 return self[name]
-> 3081             return object.__getattribute__(self, name)
   3082 
   3083     def __setattr__(self, name, value):

AttributeError: 'Series' object has no attribute 'isna'

**Comment by mattpitkin** [comment]
Hi @fleaf5 , can you check what pandas version you have installed, e.g.

```python
import pandas
print(pandas.__version__)
```

psrqpy required that the version is at least 0.22, so if the version isn't new enough try:

```
pip install --upgrade pandas
```

or

```
pip install pandas==0.22
```

**Comment by mattpitkin** [comment]
Closing this issue.
