### ISSUE TITLE
Producing ppdot diagram for a list of pulsars

### ISSUE THREAD

**Issue by mlower** [mattpitkin/psrqpy#56]
Hello, I've noticed the latest versions of `psrqpy` only create ppdot diagrams for the full catalogue, rather than just the specific pulsars that are queried. I think this is because the `query_table()` function returns the entire catalogue, as opposed to just the pulsars passed to `QueryATNF`. 

Is it possible to [re]introduce the ability to only plot pulsars of interest in the ppdot diagram?

**Comment by mattpitkin** [comment]
I think I've fixed this in #57. I'll create new release with this fix, but do let me know if there are any problems.
