### ISSUE TITLE
AstropyDeprecationWarning: Galactocentric frame default parameters

### ISSUE THREAD

**Issue by dbkeitel** [mattpitkin/psrqpy#63]
Hi @mattpitkin with psrqpy-1.0.7 and astropy-4.0.1.post1 I'm getting the following warning:
> WARNING: AstropyDeprecationWarning: In v4.1 and later versions, the Galactocentric frame will adopt default parameters that may update with time. An updated default parameter set is already available through the astropy.coordinates.galactocentric_frame_defaults ScienceState object, as described in but the default is currently still set to the pre-v4.0 parameter defaults. The safest way to guard against changing default parameters in the future is to either (1) specify all Galactocentric frame attributes explicitly when using the frame, or (2) set the galactocentric_frame_defaults parameter set name explicitly. See http://docs.astropy.org/en/latest/coordinates/galactocentric.html for more information. [astropy.coordinates.builtin_frames.galactocentric]

**Comment by mattpitkin** [comment]
Thanks for this @dbkeitel. I'll take a look and check think about setting defaults to make things consistent with psrcat, or maybe just use the `pre-v4.0` defaults.
