### ISSUE TITLE
Automate publishing to PyPI with github workflow

### ISSUE THREAD

**Issue by mattpitkin** [mattpitkin/psrqpy#72]
Rather than manually uploading new versions to PyPI I can used a github workflow to do this (see https://github.com/pypa/gh-action-pypi-publish).

**Comment by dbkeitel** [comment]
You can see a working example here: https://github.com/PyFstat/PyFstat/blob/master/.github/workflows/integration.yml#L51

In that case we decided to have it at the end of the standard integration test action, but with an `if` statement to only trigger on tagged releases; alternatively it can be a stand-alone action of course, but then one has to be even more careful to remember to only tag a release after the latest commit has passed any tests. ;)
