### ISSUE TITLE
ATNF typo causing QueryATNF to fail

### ISSUE THREAD

**Issue by astrophysically** [mattpitkin/psrqpy#73]
The Pulsar J1623+5850 was recently updated in the ATNF catalog to include a mistake in the DECJ value:

+58:5015.77

This auses QueryATNF to fail and even when trying to apply conditions to filter out this problematic pulsar, it seems the query still fails. Likely it is reading in the entire table before filtering.

The error in the pulsar's data entry has been reported, but is there a work-around in the meantime?

**Comment by mattpitkin** [comment]
Thanks for reporting this. Dick Manchester's usually pretty quick at fixing issues, so hopefully it'll be corrected soon. In #74 I've caught the exception that causes the catalogue parsing to fail, which happened when trying to convert the DECJ string to degrees. It now just fills in the RAJD and DECJD values with NaNs in this case.

**Comment by mattpitkin** [comment]
I've merge the PR so the fix should be in master now. I'll make a new release soon, so it is incorporated into the PyPI and conda installable versions.

**Comment by mattpitkin** [comment]
Resolved by #74.
