### ISSUE TITLE
can't find some PSRs in 1.0.11 output that I can see on the web table

### ISSUE THREAD

**Issue by dbkeitel** [mattpitkin/psrqpy#75]
Hi @mattpitkin , I've updated to psrqpy 1.0.11 and am doing
```
pulsars_atnf = psrqpy.QueryATNF(params=['name','jname','raj','decj','posepoch','rajd','decjd','F0','F1','F2','F3','pepoch','binary','dist','age']).table
```
as before. I then ran into the problem that `J1706-4434` which got recently added to the glitch table cannot be matched against that main catalog table using a `np.where` loop I had been using.

So I went to the web catalog and searched manually, and actually there I can see it as entry 1322. I then went through the difference of the web-generated table against the one from `psrqpy` from the top and already number 6 (`J0021-0909`) from the web version does not show up in the `psrqpy` output either.

Any idea what's going on? Is there maybe some local cache I need to purge of old catalog versions?

**Comment by mattpitkin** [comment]
When I do the query both those pulsars seem to be present. Try adding the `checkupdate=True` argument into your query.

**Comment by dbkeitel** [comment]
Thanks, that resolved it!
