### ISSUE TITLE
Add support for multiple associations

### ISSUE THREAD

**Issue by tycohen** [mattpitkin/psrqpy#76]
As far as I can tell from the docs, there's no way to view the full entry for associations, only the first one. How difficult would it be to return the full `ASSOC` string? I could take a crack at this if it's not going to require a large amount of refactoring.

**Comment by mattpitkin** [comment]
Hi @tycohen, you can access the full original ASSOC string using the `ASSOC_ORIG` key in the returned query table https://github.com/mattpitkin/psrqpy/blob/3208300fee8050eb97c4470102b91ffa37ca059e/psrqpy/search.py#L1056. I should add something to the docs about this!

**Comment by tycohen** [comment]
Exactly what I needed, thanks!
