### ISSUE TITLE
'SURVEY' condition raises UndefinedVariableError or returns empty table

### ISSUE THREAD

**Issue by tycohen** [mattpitkin/psrqpy#87]
A query with a survey condition formatted as described in Sec. 2.3 of
https://www.atnf.csiro.au/research/pulsar/psrcat/psrcat_help.html
 `QueryATNF(params=['NAME'], condition='survey(pksmb)')`
raises an `UndefinedVariableError`.

`SURVEY` appears to be supported in the list of logical conditions in psrqpy.utils but 
`QueryATNF(params=['NAME'], condition='survey == "pksmb"')`
returns an empty table.

**Comment by mattpitkin** [comment]
Which version of psrqpy are you using? If I use version 1.1.1 and do:
```python
q = QueryATNF(params=['NAME'], condition='survey(pksmb)')
```

then `q.table` returns:

```python
q.table
<Table length=1121>
   NAME   
  str11   
----------
J0725-1635
J0729-1448
J0729-1836
J0733-2345
J0737-2202
J0742-2822
J0820-4114
J0828-3417
J0831-4406
J0834-4159
       ...
J1921+0812
J1921+1419
J1926+0737
J1926+1434
J1927+0911
J1930+1316
J1932+1059
J1933+1304
J1937+1505
J1941+1341
```

**Comment by tycohen** [comment]
You're right, sorry. I thought I had the most recent version but a local installation was overriding it. This works, thanks.
